### ISSUE TITLE
Feature req:

### ISSUE THREAD

**Issue by knightmob** [kamyroll/Kamyroll-Tauri#10]
Bruh, this app is lit! thanks for making this dev, although I know that this is a fresh app and still on dev stage, but can I ask for marking option? Ability to add anime in the Library? like the category. Btw your app is lit! Keep up the good work dev!

**Comment by Bilnaa** [comment]
#5 it will be a thing when I get to implement things like Anime Trackers, you can follow the issue by clicking on the #. Thanks a lot for your feedbacks !!!
