### ISSUE TITLE
Some animes doesnt work

### ISSUE THREAD

**Issue by k3n4i70** [kamyroll/Kamyroll-Tauri#11]
Some animes like "Haven't you heard? I'm Shakomoto" doesn't work I don't actually know if there other that don't work.
And also Is it possible to add intro and outro skipper?

**Comment by Bilnaa** [comment]
@k3n4i70 on what platorm is it not working ? and it's planned

**Comment by k3n4i70** [comment]
I think its from the API, not working on Saikou and Tauri

**Comment by Bilnaa** [comment]
They're not available on the US catalog use ADN for that anime
![image](https://user-images.githubusercontent.com/43651360/205512116-09765444-f5b5-43c0-98b9-daee3e8553a2.png)
