### ISSUE TITLE
Play in external player

### ISSUE THREAD

**Issue by rollingmoai** [kamyroll/Kamyroll-Tauri#16]
- Related to #15

Add a button to conveniently play episode/season in an external player, allowing the user to set a preferred custom player.

**Comment by Bilnaa** [comment]
No

**Comment by rollingmoai** [comment]
Why?

**Comment by Bilnaa** [comment]
The app is not meant to be used as a GUI but as a full app if you want to use an external player use either the powershell script or the bash script. If you want tho if you click on the download button on the last beta versions you'll be able to get the link and put it into the player you want.
