### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rollingmoai** [kamyroll/Kamyroll-Tauri#18]
What is the license of this repo? There isn't a license file available, so I assume it's `All Rights Reserved`?

> Although in the package.json, it states `ISC`:
https://github.com/kamyroll/Kamyroll-Tauri/blob/677c4769944b2876210f38e0f3ca90ddc5ffb241/package.json#L56

**Comment by Bilnaa** [comment]
I will think about finding a licence that suits well with the project, do you have any ideas on what licence i could use ?

**Comment by rollingmoai** [comment]
A GPL-3.0 (copyleft) license, like in https://github.com/kamyroll/pwsh-kamyroll?
![image](https://user-images.githubusercontent.com/75471378/210193796-51839ebe-c105-40f4-8c4d-bd9f43703b8e.png)

**Comment by Bilnaa** [comment]
I went for Mozilla’s MPL-2.0
https://github.com/kamyroll/Kamyroll-Tauri/commit/484e2bbe84aae4616233c150d84cb2843fdfbca0

**Comment by rollingmoai** [comment]
@Bilnaa can you also update https://github.com/kamyroll/Kamyroll-Tauri/blob/b8eafb6d18b73e818e71e738b2ec9e2445f72e1a/src-tauri/Cargo.toml and https://github.com/kamyroll/Kamyroll-Tauri/blob/dev/package.json with the new license?

**Comment by Bilnaa** [comment]
Sure I already did the package.json I forgot the cargo.toml since it's really that important
