### ISSUE TITLE
Dont load

### ISSUE THREAD

**Issue by Skyyy1314** [kamyroll/Kamyroll-Tauri#27]
The kamyroll api doesn't work at all, it stays on an eternal loading screen

**Comment by hyugogirubato** [comment]
Try CTR+T maybe 🤔

**Comment by Bilnaa** [comment]
WIN+R => %appdata% => delete com.nabil.kamyroll

**Comment by Skyyy1314** [comment]
@Bilnaa this archive does not exist

**Comment by Skyyy1314** [comment]
![image](https://user-images.githubusercontent.com/89951576/212780878-f1e4f8b8-a728-49dc-95fe-b312b75524c5.png)
@Bilnaa

**Comment by Bilnaa** [comment]
and in \AppData\Local\com.nabil.kamyroll ?

**Comment by josefredohd** [comment]
@Skyyy1314 It works for me.

**Comment by Skyyy1314** [comment]
> and in \AppData\Local\com.nabil.kamyroll ?

oh

**Comment by Skyyy1314** [comment]
@Bilnaa I delete the file but it's no use, the app still doesn't work, one question, how do I install the API? just run the file, right?

**Comment by Bilnaa** [comment]
@Skyyy1314 you don't install the api you should be able to install the software just like that, it's an odd issue.

**Comment by Skyyy1314** [comment]
@Bilnaa can you send the link for me? please

**Comment by Bilnaa** [comment]
The link of what ? It's already on the GitHub releases page, take the last one.

**Comment by Skyyy1314** [comment]
![image](https://user-images.githubusercontent.com/89951576/212913182-f3596d64-a350-4854-b1f7-6138c706128f.png)
@Bilnaa Do I just need to install and run this?

**Comment by Bilnaa** [comment]
Yes you install the one that finihses by en-US.msi and u should be good to go.

**Comment by Skyyy1314** [comment]
@Bilnaa 
![image](https://user-images.githubusercontent.com/89951576/212913875-91e84d67-c8db-43bd-8f0c-7a3ff4930fff.png)
LOOK THIS, DONT LOAD!!!!

**Comment by Bilnaa** [comment]
Refresh the page...

**Comment by Skyyy1314** [comment]
how?

**Comment by Skyyy1314** [comment]
oh... works

**Comment by Skyyy1314** [comment]
thank you :D

**Comment by Skyyy1314** [comment]
<333
