### ISSUE TITLE
Neko-Sama doesn't work

### ISSUE THREAD

**Issue by kuriipa** [kamyroll/Kamyroll-Tauri#30]
im trying to watch something on neko-sama but on every anime give me this error.
some fix?

![images](https://user-images.githubusercontent.com/75102857/213953114-f81e50dd-323f-4369-89a4-0ab9026e8ac2.png)

**Comment by Bilnaa** [comment]
It's an issue with the api sadly I can't do anything about it you'll have to wait or use another platform
