### ISSUE TITLE
Full screen on the missing application

### ISSUE THREAD

**Issue by LeinadUchiha** [kamyroll/Kamyroll-Tauri#4]
With the update 1.0.1 the function of having the full screen inside the application has disappeared, I don't know if it is a bug or they are going to remove it definitively?
![image](https://user-images.githubusercontent.com/82487805/200094077-522f1b15-713e-4619-9a50-3fe2b616e575.png)

**Comment by Bilnaa** [comment]
I removed it from the windows version it was meant for macOS machines since the fullscreen isn't supported on there. Do you think it would be a good idea to bring it back ? (cuz you can use PIP with hardsubs)

**Comment by LeinadUchiha** [comment]
If I think it should return although the pip is very useful it can be annoying to always stay above and has a size limit, so I think the full screen option in the application should return.

One thing I don't know if it is possible would be to have "Explore" options to be able to have the lists like the Popular anime list or the one that I think is the most useful which is the Newest one that allows to have a list of the last chapters added.

![image](https://user-images.githubusercontent.com/82487805/200124559-b34c4b56-c58d-451e-9a66-c3ff6da04762.png)

**Comment by Bilnaa** [comment]
I will try to add that through AniList but I can't get that natively from crunchyroll sadly

**Comment by LeinadUchiha** [comment]
Yes I understand and it would be great that implementation, by the way, will the full screen function be back in the application?

**Comment by LeinadUchiha** [comment]
there is another thing that I have also noticed, that now in windowed mode the anime are not seen complete are cut at the top and can only be seen complete to be in full screen or pip mode, which is also another thing in pip mode the subtitles will not load if you have not selected the audio in jap-language, if placed in subtitles in pip mode will not appear.

window mode
![image](https://user-images.githubusercontent.com/82487805/200149992-7c11fc0f-4497-4e5c-9841-bbf8a0c0ed7d.png)

full screen

![image](https://user-images.githubusercontent.com/82487805/200150009-c84b4379-ddc5-486f-989f-faca2d566378.png)

**Comment by Bilnaa** [comment]
With HTML 5 players subtitles don't port to the pip window

**Comment by Bilnaa** [comment]
The feature is now fully added and supported for all the platforms #6
